-- =====================================================
-- SCRIPT: Crear tabla REND_TIPO_CAMBIO
-- =====================================================
-- Esta tabla almacena los tipos de cambio diarios
-- para conversión de monedas en modo OFFLINE
-- =====================================================

-- -----------------------------------------------------
-- HANA (modo ONLINE con SAP HANA)
-- -----------------------------------------------------
CREATE COLUMN TABLE "REND_TIPO_CAMBIO" (
  "U_IdTipoCambio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "U_Fecha" DATE NOT NULL,
  "U_Moneda" NVARCHAR(10) NOT NULL,
  "U_Tasa" DECIMAL(18,6) NOT NULL,
  "U_Activo" NVARCHAR(1) DEFAULT 'Y',
  UNIQUE ("U_Fecha", "U_Moneda")
);

COMMENT ON TABLE "REND_TIPO_CAMBIO" IS 'Tipos de cambio diarios para conversión de monedas';
COMMENT ON COLUMN "REND_TIPO_CAMBIO"."U_IdTipoCambio" IS 'ID autoincremental';
COMMENT ON COLUMN "REND_TIPO_CAMBIO"."U_Fecha" IS 'Fecha del tipo de cambio';
COMMENT ON COLUMN "REND_TIPO_CAMBIO"."U_Moneda" IS 'Código de moneda (USD, EUR, etc.)';
COMMENT ON COLUMN "REND_TIPO_CAMBIO"."U_Tasa" IS 'Tasa: cuántos BOB = 1 unidad de moneda';
COMMENT ON COLUMN "REND_TIPO_CAMBIO"."U_Activo" IS 'Y=Activo, N=Inactivo';

-- Índice para búsquedas por fecha/moneda
CREATE INDEX "IDX_TIPO_CAMBIO_FECHA_MONEDA" ON "REND_TIPO_CAMBIO" ("U_Fecha", "U_Moneda");

-- -----------------------------------------------------
-- PostgreSQL (modo OFFLINE)
-- -----------------------------------------------------
/*
CREATE TABLE REND_TIPO_CAMBIO (
  U_IdTipoCambio SERIAL PRIMARY KEY,
  U_Fecha DATE NOT NULL,
  U_Moneda VARCHAR(10) NOT NULL,
  U_Tasa DECIMAL(18,6) NOT NULL,
  U_Activo CHAR(1) DEFAULT 'Y',
  UNIQUE (U_Fecha, U_Moneda)
);

COMMENT ON TABLE REND_TIPO_CAMBIO IS 'Tipos de cambio diarios para conversión de monedas';
COMMENT ON COLUMN REND_TIPO_CAMBIO.U_IdTipoCambio IS 'ID autoincremental';
COMMENT ON COLUMN REND_TIPO_CAMBIO.U_Fecha IS 'Fecha del tipo de cambio';
COMMENT ON COLUMN REND_TIPO_CAMBIO.U_Moneda IS 'Código de moneda (USD, EUR, etc.)';
COMMENT ON COLUMN REND_TIPO_CAMBIO.U_Tasa IS 'Tasa: cuántos BOB = 1 unidad de moneda';
COMMENT ON COLUMN REND_TIPO_CAMBIO.U_Activo IS 'Y=Activo, N=Inactivo';

CREATE INDEX IDX_TIPO_CAMBIO_FECHA_MONEDA ON REND_TIPO_CAMBIO (U_Fecha, U_Moneda);
*/

-- -----------------------------------------------------
-- DATOS DE EJEMPLO (USD)
-- -----------------------------------------------------
-- Ajustar según tasas reales
/*
INSERT INTO "REND_TIPO_CAMBIO" ("U_Fecha", "U_Moneda", "U_Tasa", "U_Activo")
VALUES 
  ('2026-01-01', 'USD', 6.96, 'Y'),
  ('2026-01-02', 'USD', 6.97, 'Y'),
  ('2026-01-03', 'USD', 6.95, 'Y');
*/
